[tool.poetry]
name = "crowdreviews"
version = "0.1.0"
description = ""
authors = ["Chintal <chintaldraval@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1"
django-environ = "^0.9.0"
mysqlclient = "^2.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
