# Generated by Django 3.2.5 on 2022-09-07 18:07

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token_key',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=12),
        ),
    ]
